---

- name: Install Apache
  hosts: all
  tasks:
  
  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]

  - name: Install apache2 and php support package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu"]

  - name: Update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution in ["RedHat"]

  - name: Install httpd and php support package
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["RedHat"]
