---

- name: Install updates
  hosts: all
  pre_tasks:

  - name: Update repository cache (RHEL)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["RedHat"]

  - name: Update repository cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Ubuntu"]

  - name:  Update repository cache (SLES)
    tags: always
    zypper:
      name: '*'
      state: latest
    changed_when: false
    when: ansible_distribution in ["SLES"]


- hosts: all
  roles:
    - base

- hosts: web_servers
  roles:
    - web_servers

- hosts: db_servers
  roles: 
    - db_servers

- hosts: file_servers
  roles:
    - file_servers
