---

- name: Install updates
  hosts: all
  pre_tasks:

  - name: Install updates (RHEL)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["RedHat"]

  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]

  - name: Install updates (SLES)
    tags: always
    zypper:
      name: '*'
      state: latest
    when: ansible_distribution in ["SLES"]
  

- name: Install apache on web_servers
  hosts: web_servers
  tasks:

  - name: Install apache2 and php support package (Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu"]

  - name: Install httpd and php support package (RHEL)
    tags: apache,httpd,rhel
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["RedHat"]


- name: Install DB (mariadb) package
  hosts: db_servers
  tasks:

  - name: Install mariadb DB (RHEL)
    tags: db,mariadb,rhel
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["RedHat"]

  - name: Install mariadb DB (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu"]

- name: Install samba
  hosts: file_servers
  tasks:

  - name: Install samba server package
    tags: samba
    zypper:
      name: samba
      state: latest
    when: ansible_distribution in ["SLES"]
