---

- name: Install updates
  hosts: all
  pre_tasks:

  - name: Update repository cache (CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["CentOS"]

  - name: Update repository cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Ubuntu"]


- hosts: all
  roles:
    - base

- hosts: web_servers
  roles:
    - web_servers

- hosts: db_servers
  roles: 
    - db_servers

- hosts: file_servers
  roles:
    - file_servers
