- name: Install apache2 and php support package (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Ubuntu"]

- name: Install httpd and php support package (RHEL)
  tags: apache,httpd,rhel
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution in ["RedHat"]

- name: Copy default html file for apache
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Start httpd (RHEL)
  tags: httpd,apache,rhel
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution in ["RedHat"]

- name: Change email address in index.html file
  tags: httpd,apache,rhel
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin pytamce@pytamce.net
  when: ansible_distribution in ["RedHat"]
  register: httpd

- name: Restart httpd (RHEL)
  tags: httpd,apache,rhel
  service:
    name: httpd
    state: restarted
  when: httpd.changed
