- name: Install apache2 and php support package (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution in ["Ubuntu"]

- name: Install httpd and php support package (RHEL)
  tags: apache,httpd,rhel
  dnf:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution in ["RedHat"]

- name: Copy default html file for apache
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Start httpd (RHEL)
  tags: httpd,apache,rhel
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  when: ansible_distribution in ["RedHat"]

- name: Change email address in index.html file
  tags: httpd,apache,rhel
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin pytamce@pytamce.org
  when: ansible_distribution in ["RedHat"]
  notify: restart_apache
