- name: Add key to pytamce user
  authorized_key:
    user: pytamce
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTel/Ny4DINPbXlXLOq9ZLueBfDrH8wCQnGxqN7QacGEahfrDuAiVsgzMy5/nhy/heAdstvMBhiTEfkHHCrOmxf2dr6XfgkwJ8BD6G/tKpsINlEmcklUhLfbyc5D8SK1s48d+gl9/4ZvBtd2grIpJ+fdSfoSI+SyXvfuomtK94B3UFHZbB8nJNhxTZfOirgjyXwymVOd19S7N2UNI+hL12gL2LROe5wrK3DE9hRCbo+2FqH7dQAlhSe9XtfufE9oqddsJkE9REfKdL1U5vppUxuw4/7XiyCg4bEwDBEHj7zKDkl3fzmGImZJfdDREYHX5S/vLRJbfzl79iNdmZax59 root@master"

- name: Generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
