- name: Install mariadb DB (CentOS)
  tags: db,mariadb,centos
  yum:
    name: mariadb
    state: latest
  when: ansible_distribution in ["CentOS"]

- name: Install mariadb DB (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution in ["Ubuntu"]
